[project]
name = "simple-tkinter"
version = "0.0.1"
description = "Simple and nice wrapper around tkinter for every non-EOL python version"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.ruff]
builtins = ["_", "__"]
cache-dir = "./.cache/ruff"
indent-width = 4
line-length = 88

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
quote-style = "double"

[tool.pyright]
reportExplicitAny = false
reportAny = false
strictDictionaryInference = true
strictListInference = true
strictSetInference = true
enableTypeIgnoreComments = true
reportImplicitOverride = false
reportUninitializedInstanceVariable = false
reportUnnecessaryIsInstance = false
reportUnreachable = false
reportIncompatibleMethodOverride = false

[[tool.pyright.executionEnvironments]]
root = "."
pythonVersion = "3.9"

[dependency-groups]
dev = ["ipython>=8.18.1", "pytest>=8.4.2"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
case-sensitive = false
combine-as-imports = true
from-first = false
length-sort = true
lines-after-imports = 2
lines-between-types = 1
split-on-trailing-comma = false
order-by-type = true
required-imports = ["from __future__ import annotations"]
default-section = "third-party"
known-first-party = ["simple-tkinter"]
section-order = [
  "future",
  "testing",
  "first-party",
  "local-folder",
  "third-party",
  "standard-library",
]

[tool.ruff.lint.isort.sections]
testing = ["pytest"]

[tool.docformatter]
style = "sphinx"
in-place = true
wrap-summaries = 88
wrap-descriptions = 88
force-wrap = false
blank = true
pre-summary-newline = true
pre-summary-space = false
# make-summary-multi-line = false
close-quotes-on-newline = true

[tool.pytest.ini_options]
python_files = ["test_*.py", "*.py"]
addopts = ["--tb=short"]
